import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {themes as prismThemes} from 'prism-react-renderer';

// Docs site for propeller-v2-vue-ui. It is the presentation layer over the
// package's hand-written guides, an auto-generated TypeDoc API reference, and
// Storybook. Mirrors the propeller-v2-react-ui docs site.
//
// Two reference surfaces, by design:
//  - The TypeDoc "API reference" (content/api/**, generated by
//    `npm run gen:api` from the pure-TS headless surface: composables, the
//    provider, the SDK seam, utilities and types).
//  - Storybook's per-component prop tables — the `.vue` Single-File
//    Components cannot be read by TypeDoc, so their props are documented
//    there; this site links out to Storybook for them.

const config: Config = {
  title: 'Propeller Vue UI',
  tagline: 'Vue 3 component library for Propeller Commerce storefronts',
  favicon: 'img/favicon.png',

  // GitHub Pages project site — mirrors the SDK / React-UI docs setup.
  url: 'https://propeller-commerce.github.io',
  baseUrl: '/propeller-v2-vue-ui/',
  organizationName: 'propeller-commerce',
  projectName: 'propeller-v2-vue-ui',
  trailingSlash: false,

  // `warn` not `throw`: the TypeDoc-generated API pages contain many
  // cross-reference links and the occasional fragile anchor; a broken link
  // there should not fail the whole docs build.
  onBrokenLinks: 'warn',
  onBrokenAnchors: 'warn',
  markdown: {hooks: {onBrokenMarkdownLinks: 'warn'}},

  i18n: {defaultLocale: 'en', locales: ['en']},

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'content', // docs live in docs/content (config files sit in docs/)
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
        },
        blog: false,
        theme: {customCss: './src/css/custom.css'},
        sitemap: {changefreq: 'weekly', priority: 0.5},
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/social-card.png',
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true,
      disableSwitch: false,
    },
    navbar: {
      title: '',
      logo: {
        alt: 'Propeller',
        src: 'img/logo.png',
        srcDark: 'img/logo-dark.png',
        height: 30,
      },
      items: [
        {to: '/getting-started', label: 'Getting started', position: 'left'},
        {to: '/guides/api/overview', label: 'API integration', position: 'left'},
        {to: '/components', label: 'Components', position: 'left'},
        {to: '/api', label: 'API reference', position: 'left'},
        {to: '/contributing', label: 'Contributing', position: 'left'},
        {
          href: 'https://gitlab.com/propellor-eu/cloud/frontend/ui/propeller-v2-vue-ui',
          label: 'GitLab',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Getting started', to: '/getting-started'},
            {label: 'The SDK seam', to: '/sdk-seam'},
            {label: 'Styling', to: '/styling'},
            {label: 'Nuxt & SSR', to: '/nuxt-ssr'},
          ],
        },
        {
          title: 'Reference',
          items: [
            {label: 'API integration', to: '/guides/api/overview'},
            {label: 'Component reference', to: '/components'},
            {label: 'API reference', to: '/api'},
            {label: 'Storybook', to: '/storybook'},
            {label: 'Contributing', to: '/contributing'},
          ],
        },
        {
          title: 'Resources',
          items: [
            {
              label: 'React UI docs',
              href: 'https://propeller-commerce.github.io/propeller-v2-react-ui/',
            },
            {
              label: 'SDK docs',
              href: 'https://propeller-commerce.github.io/propeller-sdk-v2/',
            },
            {
              label: 'Propeller Commerce',
              href: 'https://propeller-commerce.com',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Propeller Commerce.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json'],
    },
  } satisfies Preset.ThemeConfig,

  plugins: [
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexDocs: true,
        indexBlog: false,
        docsRouteBasePath: '/',
      },
    ],
  ],
};

export default config;
