import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The TypeDoc API reference sidebar is generated by `npm run gen:api` into
// content/api/typedoc-sidebar.cjs. That step runs in `prestart`/`prebuild`,
// so the file is always present for a real build — but guard the require so
// editing sidebars.ts (or running tooling) before a first generation does
// not crash.
let typedocItems: any[] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const typedocSidebar = require('./content/api/typedoc-sidebar.cjs');
  typedocItems = typedocSidebar.items ?? typedocSidebar ?? [];
} catch {
  typedocItems = [];
}

// Manual sidebar — the docs set is small and curated, so an explicit order
// reads better than autogeneration. Each id is the content/*.mdx basename.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['getting-started', 'sdk-seam', 'styling', 'nuxt-ssr'],
    },
    {
      type: 'category',
      label: 'API integration',
      collapsed: false,
      items: [
        'guides/api/overview',
        'guides/api/cart',
        'guides/api/auth',
        'guides/api/catalog',
        'guides/api/orders',
        'guides/api/b2b',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'components',
        'storybook',
        ...(typedocItems.length
          ? [
              {
                type: 'category' as const,
                label: 'API reference',
                items: typedocItems,
              },
            ]
          : []),
      ],
    },
    'contributing',
  ],
};

export default sidebars;
